source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               models/,\
               lib/pmml-evaluator-1.7.7.jar,\
               lib/pmml-evaluator-metro-1.7.7.jar,\
               lib/pmml-model-1.7.7.jar
